# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# Apply to all files without commiting:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args:
          - --maxkb=128
      - id: check-ast # Simply checks whether the files parse as valid python
      - id: check-builtin-literals # Requires literal syntax when initializing empty or zero python builtin types
      - id: check-case-conflict # Check for filenames that would conflict on a case-insensitive filesystem
      - id: check-docstring-first # Checks a common error of defining a docstring after code
      - id: check-executables-have-shebangs # Ensures that (non-binary) executables have a shebang
      - id: check-json # Checks json files for parseable syntax
      - id: check-merge-conflict # Checks for files that contain merge conflict strings
      - id: check-xml # Checks xml files for parseable syntax
      - id: check-yaml # Checks yaml files for parseable syntax
      - id: debug-statements # Check for debugger imports and py37+ `breakpoint()` calls in Python source.
      - id: detect-private-key # Detects the presence of private keys
      - id: end-of-file-fixer # Ensures that a file is either empty, or ends with one newline
        exclude: ".svg$"
      - id: file-contents-sorter # Sorts the lines in specified files (defaults to alphabetical)
        args: ["--ignore-case", "--unique"]
        files: ^(requirements[-\w]*.txt)$
      - id: fix-byte-order-marker # Forbid UTF-8 byte-order
      - id: mixed-line-ending # Replaces or checks mixed line ending
        args: ["--fix=lf"]
      - id: name-tests-test # Verifies that test files are named correctly
        args:
          - --django
        exclude: ^tests/testapp|^tests/management/|^tests/collisions/|^tests/pythonrc.py
      - id: pretty-format-json # Sets a standard for formatting json files
      - id: trailing-whitespace # Trims trailing whitespace
        exclude: ".md$|.email$"

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py310-plus]

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3.9

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.13.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==22.3.0]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings]

  - repo: https://github.com/PyCQA/isort
    rev: "5.12.0"
    hooks:
      - id: isort
        args: ["--profile=black"]

  # - repo: https://github.com/miki725/importanize
  #   rev: "0.7"
  #   hooks:
  #     - id: importanize
  #       language_version: python3
  # - repo: https://github.com/PyCQA/pydocstyle
  #   rev: 6de6d938377e2db3bfe6f706fa2e3b90c412db76
  #   hooks:
  #     - id: pydocstyle
  # - repo: https://github.com/PyCQA/bandit
  #   rev: "1.6.0"
  #   hooks:
  #     - id: bandit
  # - repo: https://github.com/prettier/prettier
  #   rev: "1.18.2"
  #   hooks:
  #     - id: prettier
  #       args: ["--print-width 120"]
  #       additional_dependencies: ['prettier@1.1.0']
  # - repo: https://github.com/adrienverge/yamllint
  #   rev: "v1.16.0"
  #   hooks:
  #     - id: yamllint

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.4.2
    hooks:
      - id: forbid-crlf

  - repo: https://github.com/trbs/pre-commit-hooks-trbs
    rev: 1.2.4
    hooks:
      - id: forbid-executables
        exclude: manage.py|setup.py|docker-entrypoint.sh|compile_python.sh

  - repo: https://github.com/rtts/djhtml
    rev: "v1.5.2" # replace with the latest tag on GitHub
    hooks:
      - id: djhtml
      - id: djcss
      - id: djjs

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.991
  #   hooks:
  #     - id: mypy
  #       additional_dependencies: ["django-stubs", "pydantic"]
  #       exclude: (tests|docs)/
