services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        # Beside running uWSGI, enable the stats server on the specified address
        # and prefix stats server json output with http headers
        command: uwsgi --stats :1717 --stats-http
        container_name: manhattan_web
        env_file: .env
        ports:
            - protocol: tcp
              published: 8005
              target: 8005
            - "1717:1717"
        restart: always
        volumes:
            - ./media:/code/media:rw
            - ./cola:/code/cola:rw

    # uWSGI metrics exporter for prometheus.io
    # See <https://apsl.tech/en/blog/using-prometheus-monitoring-django-applications-kubernetes/>
    exporter:
        command: --stats.uri="http://manhattan_web:1717"
        container_name: manhattan_uwsgi_exporter
        image: timonwong/uwsgi-exporter
        ports:
            - "9117:9117"
