# Generated by Django 2.1 on 2019-03-22 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('academico_id_nk', models.IntegerField(blank=True, null=True, verbose_name='cód. académico')),
                ('rrhh_id_nk', models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='cód. RRHH')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_centro', models.CharField(blank=True, max_length=30, null=True, verbose_name='tipo de centro')),
                ('direccion', models.CharField(blank=True, max_length=140, null=True, verbose_name='dirección')),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
                ('url', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL')),
                ('nip_decano', models.PositiveIntegerField(blank=True, null=True, verbose_name='NIP del decano o director')),
                ('nombre_decano', models.CharField(blank=True, max_length=255, null=True, verbose_name='nombre del decano o director')),
                ('email_decano', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email del decano o director')),
                ('tratamiento_decano', models.CharField(blank=True, help_text='Decano/a ó director(a).', max_length=25, null=True, verbose_name='cargo')),
                ('nip_secretario', models.PositiveIntegerField(blank=True, null=True, verbose_name='NIP del secretario')),
                ('nombre_secretario', models.CharField(blank=True, max_length=255, null=True, verbose_name='nombre del secretario')),
                ('email_secretario', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email del secretario')),
                ('nip_coord_pou', models.PositiveIntegerField(blank=True, null=True, verbose_name='NIP del coordinador POU')),
                ('nombre_coord_pou', models.CharField(blank=True, max_length=255, null=True, verbose_name='nombre del coordinador POU')),
                ('email_coord_pou', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email del coordinador POU')),
                ('esta_activo', models.BooleanField(default=False, verbose_name='¿Activo?')),
            ],
        ),
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='año')),
                ('fecha_min_solicitudes', models.DateField()),
                ('fecha_max_solicitudes', models.DateField()),
                ('fecha_max_aceptos', models.DateField()),
                ('fecha_max_visto_buenos', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('academico_id_nk', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='cód. académico')),
                ('rrhh_id_nk', models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='cód. RRHH')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email del departamento')),
                ('email_secretaria', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email de la secretaría')),
                ('nip_director', models.PositiveIntegerField(blank=True, null=True, verbose_name='NIP del director')),
                ('nombre_director', models.CharField(blank=True, max_length=255, null=True, verbose_name='nombre del director')),
                ('email_director', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email del director')),
            ],
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Cód. estudio')),
                ('nombre', models.CharField(max_length=255)),
                ('esta_activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('rama', models.CharField(choices=[('B', 'Formación básica sin rama'), ('H', 'Artes y Humanidades'), ('J', 'Ciencias Sociales y Jurídicas'), ('P', 'Títulos Propios'), ('S', 'Ciencias de la Salud'), ('T', 'Ingeniería y Arquitectura'), ('X', 'Ciencias')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('nombre', models.CharField(max_length=31, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(help_text='Ver los identificadores estándar en https://spdx.org/licenses/', max_length=255, null=True, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipanteProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_nk', models.PositiveSmallIntegerField(verbose_name='Cód. plan')),
                ('nip_coordinador', models.PositiveIntegerField(blank=True, null=True, verbose_name='NIP del coordinador')),
                ('nombre_coordinador', models.CharField(blank=True, max_length=255, null=True, verbose_name='nombre del coordinador')),
                ('email_coordinador', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email del coordinador')),
                ('esta_activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indo.Centro')),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indo.Estudio')),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_corto', models.CharField(help_text='Ejemplo: PRACUZ', max_length=15)),
                ('nombre_largo', models.CharField(help_text='Ejemplo: Programa de Recursos en Abierto para Centros', max_length=127)),
                ('max_ayuda', models.PositiveSmallIntegerField(null=True, verbose_name='Cuantía máxima que se puede solicitar de ayuda')),
                ('max_estudiantes', models.PositiveSmallIntegerField(null=True, verbose_name='Número máximo de estudiantes por programa')),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indo.Convocatoria')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=31, null=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('financiacion', models.TextField(blank=True, null=True, verbose_name='Financiación solicitada')),
                ('ayuda', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ayuda solicitada')),
                ('centro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='indo.Centro')),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indo.Convocatoria')),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='indo.Departamento')),
                ('estudio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='indo.Estudio')),
                ('licencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='indo.Licencia')),
                ('linea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='indo.Linea')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indo.Programa')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indo.Evento')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indo.Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEstudio',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Cód. tipo estudio')),
                ('nombre', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='TipoParticipacion',
            fields=[
                ('nombre', models.CharField(max_length=63, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='participanteproyecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indo.Proyecto'),
        ),
        migrations.AddField(
            model_name='participanteproyecto',
            name='tipo_participacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indo.TipoParticipacion'),
        ),
        migrations.AddField(
            model_name='participanteproyecto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='linea',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indo.Programa'),
        ),
        migrations.AddField(
            model_name='estudio',
            name='tipo_estudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indo.TipoEstudio'),
        ),
        migrations.AddIndex(
            model_name='centro',
            index=models.Index(fields=['academico_id_nk'], name='indo_centro_academi_5535ce_idx'),
        ),
    ]
