# Generated by Django 2.1 on 2019-03-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('academico_id_nk', models.IntegerField(blank=True, null=True, verbose_name='cód. académico')),
                ('rrhh_id_nk', models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='cód. RRHH')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_centro', models.CharField(blank=True, max_length=30, null=True, verbose_name='tipo de centro')),
                ('direccion', models.CharField(blank=True, max_length=140, null=True, verbose_name='dirección')),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
                ('url', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL')),
                ('nip_decano', models.PositiveIntegerField(blank=True, null=True)),
                ('nombre_decano', models.CharField(blank=True, max_length=255, null=True)),
                ('email_decano', models.EmailField(blank=True, max_length=254, null=True)),
                ('tratamiento_decano', models.CharField(blank=True, max_length=25, null=True)),
                ('nip_secretario', models.PositiveIntegerField(blank=True, null=True)),
                ('nombre_secretario', models.CharField(blank=True, max_length=255, null=True)),
                ('email_secretario', models.EmailField(blank=True, max_length=254, null=True)),
                ('esta_activo', models.BooleanField(default=False, verbose_name='¿Activo?')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('academico_id_nk', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='cód. académico')),
                ('rrhh_id_nk', models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='cód. RRHH')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
                ('email_secretaria', models.EmailField(blank=True, max_length=254, null=True)),
                ('nip_director', models.PositiveIntegerField(blank=True, null=True)),
                ('nombre_director', models.CharField(blank=True, max_length=255, null=True)),
                ('email_director', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='centro',
            index=models.Index(fields=['academico_id_nk'], name='indo_centro_academi_5535ce_idx'),
        ),
    ]
