# Generated by Django 3.1 on 2021-05-28 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resolucion',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('titulo', models.CharField(max_length=255, verbose_name='título')),
                (
                    'url',
                    models.URLField(
                        help_text='Dirección de la página web. Vg: https://ae.unizar.es/?app=touz&opcion=mostrar&id=12345',
                        max_length=255,
                        verbose_name='URL',
                    ),
                ),
            ],
            options={
                'verbose_name': 'resolución',
                'verbose_name_plural': 'resoluciones',
                'ordering': ('fecha',),
            },
        ),
    ]
