# Generated by Django 3.0.2 on 2020-01-31 11:45
# https://docs.djangoproject.com/en/3.0/howto/writing-migrations/

from django.db import migrations


def add_managers_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    group, created = Group.objects.get_or_create(name="Gestores")
    if created:
        print("Creado el grupo «Gestores».")
        listar_proyectos = Permission.objects.get(codename="listar_proyectos")
        group.permissions.add(listar_proyectos)


class Migration(migrations.Migration):

    dependencies = [("indo", "0002_auto_20200131_1244")]

    operations = [migrations.RunPython(add_managers_group)]
