# Generated by Django 3.2 on 2021-05-31 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indo', '0002_resolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='ip_address',
            field=models.GenericIPAddressField(null=True, verbose_name='Dirección IP'),
        ),
        migrations.AddField(
            model_name='registro',
            name='usuario',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='registros',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
