# Generated by Django 3.2.7 on 2021-09-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0003_auto_20210531_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='esta_evaluado',
            field=models.BooleanField(null=True, verbose_name='Ha sido evaluado'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(
                help_text='Resumen sucinto del proyecto. Máximo recomendable: un párrafo de 10 líneas.<br>Si copia de Word y se le indica que ha introducido demasiados caracteres, pruebe a pegar usando Ctrl+Mayúsculas+V.',
                max_length=4095,
                null=True,
                verbose_name='Resumen',
            ),
        ),
    ]
