# Generated by Django 2.2.1 on 2019-06-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("indo", "0003_auto_20190531_1456")]

    operations = [
        migrations.RemoveField(model_name="centro", name="email_coord_pou"),
        migrations.RemoveField(model_name="centro", name="nip_coord_pou"),
        migrations.RemoveField(model_name="centro", name="nombre_coord_pou"),
        migrations.AddField(
            model_name="centro",
            name="emails_coords_pou",
            field=models.CharField(
                blank=True,
                max_length=1023,
                null=True,
                verbose_name="emails de los coordinadores POU",
            ),
        ),
        migrations.AddField(
            model_name="centro",
            name="nips_coord_pou",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="NIPs de los coordinadores POU",
            ),
        ),
        migrations.AddField(
            model_name="centro",
            name="nombres_coords_pou",
            field=models.CharField(
                blank=True,
                max_length=1023,
                null=True,
                verbose_name="nombres de los coordinadores POU",
            ),
        ),
        migrations.AddField(
            model_name="centro",
            name="unidad_gasto",
            field=models.CharField(
                blank=True, max_length=3, null=True, verbose_name="unidad de gasto"
            ),
        ),
        migrations.AddField(
            model_name="departamento",
            name="unidad_gasto",
            field=models.CharField(
                blank=True, max_length=3, null=True, verbose_name="unidad de gasto"
            ),
        ),
    ]
