# Generated by Django 3.2.4 on 2021-09-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0004_auto_20210909_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='ayuda_definitiva',
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name='Ayuda económica concedida (definitiva)'
            ),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='puntuacion',
            field=models.PositiveIntegerField(null=True, verbose_name='Puntuación obtenida'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='ayuda_concedida',
            field=models.PositiveIntegerField(
                null=True, verbose_name='Ayuda económica concedida (provisional)'
            ),
        ),
    ]
