# Generated by Django 2.2.1 on 2019-06-11 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("indo", "0005_auto_20190606_1412")]

    operations = [
        migrations.AddField(
            model_name="programa",
            name="requiere_visto_bueno",
            field=models.BooleanField(
                default="False",
                verbose_name="¿Requiere el visto bueno del director o decano?",
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="visto_bueno",
            field=models.BooleanField(null=True, verbose_name="Visto bueno"),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="centro",
            field=models.ForeignKey(
                blank=True,
                help_text="Sólo obligatorio para PIEC, PRACUZ, PIPOUZ.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="proyectos",
                to="indo.Centro",
            ),
        ),
    ]
