# Generated by Django 3.2.4 on 2021-09-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0005_auto_20210924_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='ayuda_concedida',
            new_name='ayuda_provisional',
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='notificada_resolucion_definitiva',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='notificada_resolucion_provisional',
            field=models.BooleanField(default=False),
        ),
    ]
