# Generated by Django 3.2.7 on 2021-10-05 08:24

from django.contrib.auth.management import create_permissions
from django.db import migrations


def migrate_permissions(apps, schema_editor):
    """Create the pending permissions.

    Permissions are not actually created during or after an individual migration,
    but are triggered by a post-migrate signal which is sent after the
    `python manage.py migrate` command completes successfully.

    This is necessary so that we can add the permission to a group in this migration.
    """
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=2)
        app_config.models_module = None


def add_permission_to_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    gestores = Group.objects.get(name='Gestores')

    hace_constar = Permission.objects.get(codename='hace_constar')
    gestores.permissions.add(hace_constar)


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0006_auto_20210927_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rightssupport',
            options={
                'managed': False,
                'permissions': (
                    ('gestionar_correctores', 'Puede añadir/quitar usuarios al grupo Correctores'),
                    ('asignar_correctores', 'Puede asignar un corrector de memoria a un proyecto'),
                    (
                        'hace_constar',
                        'Puede generar PDFs de constancia de participación en proyectos',
                    ),
                ),
            },
        ),
        migrations.RunPython(migrate_permissions),
        migrations.RunPython(add_permission_to_group),
    ]
