# Generated by Django 2.2.1 on 2019-06-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("indo", "0006_auto_20190611_1019")]

    operations = [
        migrations.AlterField(
            model_name="centro",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="centro",
            name="rrhh_id_nk",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="cód. RRHH"
            ),
        ),
        migrations.AlterField(
            model_name="departamento",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="departamento",
            name="rrhh_id_nk",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="cód. RRHH"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="centro", unique_together={("academico_id_nk", "rrhh_id_nk")}
        ),
        migrations.AlterUniqueTogether(
            name="departamento", unique_together={("academico_id_nk", "rrhh_id_nk")}
        ),
    ]
