# Generated by Django 3.2.8 on 2021-10-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0007_alter_rightssupport_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='fecha_max_modificacion_equipos',
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name='fecha límite para modificaciones excepcionales de los equipos de trabajo',
            ),
        ),
    ]
