# Generated by Django 3.0.6 on 2020-06-11 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0007_auto_20200528_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parte', models.PositiveSmallIntegerField(verbose_name='parte')),
                ('peso', models.PositiveSmallIntegerField(verbose_name='peso')),
                ('descripcion', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('opcion', 'Opción'), ('texto', 'Texto libre')], max_length=15, verbose_name='tipo')),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indo.Convocatoria')),
            ],
            options={
                'ordering': ('convocatoria', 'parte', 'peso'),
            },
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveSmallIntegerField(verbose_name='puntuación')),
                ('descripcion', models.CharField(max_length=255, verbose_name='descripción')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opciones', to='indo.Criterio')),
            ],
            options={
                'verbose_name': 'opción',
                'verbose_name_plural': 'opciones',
                'ordering': ('criterio__parte', 'criterio__peso', 'puntuacion'),
            },
        ),
        migrations.AlterField(
            model_name='estudio',
            name='rama',
            field=models.CharField(choices=[('B', 'Formación básica sin rama'), ('H', 'Artes y Humanidades'), ('J', 'Ciencias Sociales y Jurídicas'), ('P', 'Títulos Propios'), ('S', 'Ciencias de la Salud'), ('T', 'Ingeniería y Arquitectura'), ('X', 'Ciencias')], max_length=1, verbose_name='rama'),
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, null=True, verbose_name='texto')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indo.Criterio')),
                ('opcion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='indo.Opcion')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valoraciones', to='indo.Proyecto')),
            ],
            options={
                'verbose_name': 'valoración',
                'verbose_name_plural': 'valoraciones',
            },
        ),
    ]
