# Generated by Django 3.0.7 on 2020-06-22 06:44

from django.apps import apps as django_apps
from django.db import migrations, models


def add_permission_to_group(apps, schema_editor):
    group = apps.get_model('auth', 'Group')
    permission = apps.get_model('auth', 'Permission')

    gestores = group.objects.get(name='Gestores')
    permiso = permission.objects.get(codename='editar_aceptacion')
    gestores.permissions.add(permiso)


def geo_post_migrate_signal(apps, schema_editor):
    """Emit the post-migrate signal during the migration.

    Permissions are not actually created during or after an individual migration,
    but are triggered by a post-migrate signal which is sent after the
    `python manage.py migrate` command completes successfully.

    This is necessary because this permission is used later in this migration.
    """
    indo_config = django_apps.get_app_config('indo')
    models.signals.post_migrate.send(
        sender=indo_config,
        app_config=indo_config,
        verbosity=2,
        interactive=False,
        using=schema_editor.connection.alias,
    )


class Migration(migrations.Migration):

    dependencies = [('indo', '0008_auto_20200611_1002')]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={
                'permissions': [
                    ('listar_proyectos', 'Puede ver el listado de todos los proyectos.'),
                    ('ver_proyecto', 'Puede ver cualquier proyecto.'),
                    ('editar_proyecto', 'Puede editar cualquier proyecto en cualquier momento.'),
                    ('listar_evaluadores', 'Puede ver el listado de evaluadores.'),
                    ('editar_evaluador', 'Puede editar el evaluador de un proyecto.'),
                    ('editar_aceptacion', 'Puede editar la decisión de la Comisión Evaluadora.'),
                ]
            },
        ),
        migrations.AddField(
            model_name='proyecto',
            name='aceptacion_comision',
            field=models.BooleanField(null=True, verbose_name='Aceptación por la comisión'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ayuda_concedida',
            field=models.PositiveIntegerField(null=True, verbose_name='Ayuda económica concedida'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='observaciones',
            field=models.TextField(
                null=True, verbose_name='Observaciones para comunicar al coordinador'
            ),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tipo_gasto',
            field=models.TextField(
                help_text='Indicar los gastos autorizados indicados por la Comisión.',
                null=True,
                verbose_name='Tipo de gasto posible',
            ),
        ),
        migrations.RunPython(geo_post_migrate_signal),
        migrations.RunPython(add_permission_to_group),
    ]
