# Generated by Django 3.2.9 on 2021-11-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0008_convocatoria_fecha_max_modificacion_equipos'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='id_uxxi',
            field=models.CharField(
                help_text='Nümero de proyecto asignado en Univesitas XXI',
                max_length=15,
                null=True,
                verbose_name='Nº UXXI',
            ),
        ),
    ]
