# Generated by Django 3.0.7 on 2021-10-25 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0008_merge_20211025_0957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'permissions': [('listar_proyectos', 'Puede ver el listado de todos los proyectos.'), ('ver_proyecto', 'Puede ver cualquier proyecto.'), ('editar_proyecto', 'Puede editar cualquier proyecto en cualquier momento.'), ('listar_evaluaciones', 'Puede ver el listado de evaluaciones de los proyectos.'), ('listar_evaluadores', 'Puede ver el listado de evaluadores.'), ('editar_evaluador', 'Puede editar el evaluador de un proyecto.'), ('editar_resolucion', 'Puede modificar la resolución de la Comisión Evaluadora.'), ('listar_correctores', 'Puede ver el listado de correctores.'), ('editar_corrector', 'Puede modificar el corrector de un proyecto.'), ('ver_evaluacion', 'Puede ver la evaluación de cualquier proyecto.'), ('ver_memorias', 'Puede ver el listado y cualquier memoria de proyecto.'), ('ver_up', 'Puede ver el listado de UP y gastos de los proyectos.'), ('ver_economico', 'Puede ver/editar el cierre económico de los proyectos.')]},
        ),
    ]
