# Generated by Django 3.2.8 on 2021-12-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0009_proyecto_id_uxxi'),
    ]

    operations = [
        migrations.AddField(
            model_name='centro',
            name='email_administrador',
            field=models.EmailField(
                default='', max_length=254, null=True, verbose_name='email del administrador'
            ),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='id_uxxi',
            field=models.CharField(
                help_text='Número de proyecto asignado en Universitas XXI',
                max_length=15,
                null=True,
                verbose_name='Nº UXXI',
            ),
        ),
    ]
