# Generated by Django 3.2.8 on 2021-10-27 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0008_convocatoria_fecha_max_modificacion_equipos'),
        ('indo', '0009_auto_20211025_1338'),
    ]

    operations = [
    ]
