# Generated by Django 3.1.2 on 2020-10-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('indo', '0010_auto_20201019_1446')]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='aceptacion_coordinador',
            field=models.BooleanField(null=True, verbose_name='Aceptación por el coordinador'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(
                choices=[
                    ('ANULADO', 'Solicitud anulada'),
                    ('BORRADOR', 'Solicitud en preparación'),
                    ('SOLICITADO', 'Solicitud presentada'),
                    ('DENEGADO', 'Denegado por la comisión evaluadora'),
                    ('APROBADO', 'Aprobado por la comisión evaluadora'),
                    ('RECHAZADO', 'Rechazado por el coordinador'),
                    ('ACEPTADO', 'Aceptado por el coordinador'),
                ],
                default='BORRADOR',
                max_length=63,
            ),
        ),
    ]
