# Generated by Django 3.2.9 on 2021-12-03 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0010_auto_20211202_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='centro',
            field=models.ForeignKey(
                default=23,  # Genérico Universidad 9999 / UUU
                on_delete=django.db.models.deletion.PROTECT,
                related_name='proyectos',
                to='indo.centro',
            ),
            preserve_default=False,
        ),
    ]
