# Generated by Django 3.1.2 on 2020-10-23 08:34

from django.apps import apps as django_apps
from django.contrib.auth.management import create_permissions
from django.db import migrations, models


def migrate_permissions(apps, schema_editor):
    """Create the pending permissions.

    Permissions are not actually created during or after an individual migration,
    but are triggered by a post-migrate signal which is sent after the
    `python manage.py migrate` command completes successfully.

    This is necessary so that we can add the permission to a group in this migration.
    """
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=2)
        app_config.models_module = None


def add_permission_to_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    gestores = Group.objects.get(name='Gestores')

    add_convocatoria = Permission.objects.get(codename='add_convocatoria')
    change_convocatoria = Permission.objects.get(codename='change_convocatoria')
    gestores.permissions.add(add_convocatoria, change_convocatoria)

    add_criterio = Permission.objects.get(codename='add_criterio')
    change_criterio = Permission.objects.get(codename='change_criterio')
    delete_criterio = Permission.objects.get(codename='delete_criterio')
    gestores.permissions.add(add_criterio, change_criterio, delete_criterio)

    add_opcion = Permission.objects.get(codename='add_opcion')
    change_opcion = Permission.objects.get(codename='change_opcion')
    delete_opcion = Permission.objects.get(codename='delete_opcion')
    gestores.permissions.add(add_opcion, change_opcion, delete_opcion)


class Migration(migrations.Migration):

    dependencies = [('indo', '0011_auto_20201020_1450')]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='num_max_equipos',
            field=models.PositiveSmallIntegerField(
                default=4,
                verbose_name='número máximo de equipos en que puede participar una persona',
            ),
        ),
        migrations.RunPython(migrate_permissions),
        migrations.RunPython(add_permission_to_group),
    ]
