# Generated by Django 4.0 on 2022-01-14 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0010_merge_20211027_1413'),
        ('indo', '0011_alter_proyecto_centro'),
    ]

    operations = [
    ]
