# Generated by Django 4.0 on 2022-02-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0012_evaluadorproyecto_alter_proyecto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='prauz_tipo',
            field=models.TextField(
                blank=True,
                help_text='Nuevo o actualización de otro ya existente',
                null=True,
                verbose_name='Tipo de curso',
            ),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='contexto',
            field=models.TextField(
                blank=True,
                help_text='Necesidad a la que responde el proyecto, mejoras esperadas respecto al estado de la\n            cuestión, otros proyectos de innovación relacionados con el propuesto, conocimiento que\n            se genera y marco epistemológico o teórico que lo avala y descripción del equipo de\n            trabajo para la realización del proyecto.',
                null=True,
                verbose_name='Contexto del proyecto',
            ),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='formatos',
            field=models.TextField(
                blank=True, null=True, verbose_name='Formatos de los materiales a incluir'
            ),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='idioma',
            field=models.TextField(
                blank=True,
                help_text='Indicar el idioma de publicación y, si además, se publicará la traducción del curso\n            completo o parcial a otros idiomas',
                null=True,
                verbose_name='Idioma de publicación',
            ),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='multimedia',
            field=models.TextField(
                blank=True,
                help_text='Descripción específica y cantidad aproximada de los recursos multimedia que incluirá\n            el curso en formato video que precisen del uso de un estudio de grabación',
                null=True,
                verbose_name='Elementos multimedia e innovadores',
            ),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='objetivos',
            field=models.TextField(
                blank=True,
                help_text='Señalando también los relacionados con los Objetivos de Desarrollo Sostenible',
                null=True,
                verbose_name='Objetivos del Proyecto',
            ),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='ramas',
            field=models.TextField(
                blank=True,
                help_text='Artes y Humanidades, Ciencias, Ciencias de la Salud, Ciencias Sociales y Jurídicas,\n            Ingeniería y Arquitectura, o Transversal',
                null=True,
                verbose_name='Rama de conocimiento',
            ),
        ),
    ]
