# Generated by Django 4.0 on 2022-02-03 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0012_evaluadorproyecto_alter_proyecto_options_and_more'),
        ('indo', '0012_merge_20220114_1425'),
    ]

    operations = [
    ]
