# Generated by Django 4.0 on 2022-02-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0013_proyecto_prauz_tipo_alter_proyecto_contexto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='prauz_contenido',
            field=models.TextField(
                blank=True, null=True, verbose_name='Breve descripción del contenido del curso'
            ),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='prauz_titulo',
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name='Título del curso'
            ),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='prauz_tipo',
            field=models.CharField(
                blank=True,
                choices=[
                    ('Nuevo', 'Nuevo'),
                    ('Actualización de otro ya existente', 'Actualización de otro ya existente'),
                ],
                max_length=34,
                null=True,
                verbose_name='Tipo de curso',
            ),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='ramas',
            field=models.CharField(
                blank=True,
                choices=[
                    ('Artes y Humanidades', 'Artes y Humanidades'),
                    ('Ciencias Sociales y Jurídicas', 'Ciencias Sociales y Jurídicas'),
                    ('Ciencias de la Salud', 'Ciencias de la Salud'),
                    ('Ingeniería y Arquitectura', 'Ingeniería y Arquitectura'),
                    ('Ciencias', 'Ciencias'),
                    ('Transversal', 'Transversal'),
                ],
                max_length=767,
                null=True,
                verbose_name='Rama de conocimiento',
            ),
        ),
    ]
