# Generated by Django 4.0 on 2022-02-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0013_merge_20220203_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='area',
            field=models.CharField(choices=[('B', 'Formación básica sin rama'), ('H', 'Artes y Humanidades'), ('J', 'Ciencias Sociales y Jurídicas'), ('P', 'Títulos Propios'), ('S', 'Ciencias de la Salud'), ('T', 'Ingeniería y Arquitectura'), ('X', 'Ciencias')], default='B', max_length=1),
        ),
    ]
