# Generated by Django 4.0.2 on 2022-02-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0014_proyecto_prauz_contenido_proyecto_prauz_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(
                help_text='Resumen sucinto del proyecto. Máximo recomendable: un párrafo de 10 líneas.<br>Si copia de Word y se le indica que ha introducido demasiados caracteres, pruebe a pegar usando Ctrl+Mayúsculas+V.',
                max_length=4095,
                null=True,
                verbose_name='Descripción',
            ),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='metodos_estudio',
            field=models.TextField(
                blank=True,
                help_text='Métodos y técnicas utilizadas, características de la muestra, actividades previstas por los estudiantes y por el equipo del proyecto, así como calendario de actividades.',
                null=True,
                verbose_name='Métodos de estudio/experimentación y trabajo de campo',
            ),
        ),
    ]
