# Generated by Django 4.0 on 2022-02-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0014_proyecto_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='area',
            field=models.CharField(default='B', max_length=1),
        ),
    ]
