# Generated by Django 3.1.5 on 2021-02-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('indo', '0014_auto_20201030_1510')]

    operations = [
        migrations.AlterUniqueTogether(name='centro', unique_together=set()),
        migrations.AlterUniqueTogether(name='departamento', unique_together=set()),
        migrations.AddConstraint(
            model_name='centro',
            constraint=models.UniqueConstraint(
                fields=('academico_id_nk', 'rrhh_id_nk'), name='centro-unique-academico-rrhh'
            ),
        ),
        migrations.AddConstraint(
            model_name='departamento',
            constraint=models.UniqueConstraint(
                fields=('academico_id_nk', 'rrhh_id_nk'), name='departamento-unique-academico-rrhh'
            ),
        ),
        migrations.AddConstraint(
            model_name='memoriarespuesta',
            constraint=models.UniqueConstraint(
                fields=('proyecto_id', 'subapartado_id'), name='unique-proyecto-subapartado'
            ),
        ),
    ]
