# Generated by Django 4.0 on 2022-02-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0015_alter_proyecto_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='area',
            field=models.TextField(),
        ),
    ]
