# Generated by Django 4.0.2 on 2022-03-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0016_alter_proyecto_contexto_alter_proyecto_continuidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterio',
            name='programas',
            field=models.JSONField(
                default=list, verbose_name='programas en los que aplicar este criterio'
            ),
        ),
    ]
