# Generated by Django 4.0 on 2022-02-24 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0014_proyecto_prauz_contenido_proyecto_prauz_titulo_and_more'),
        ('indo', '0016_alter_proyecto_area'),
    ]

    operations = [
    ]
