# Generated by Django 4.0 on 2022-02-25 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0017_merge_20220224_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='area',
        ),
    ]
