# Generated by Django 4.0.3 on 2022-03-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0017_criterio_programas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='evaluador',
        ),
        migrations.AlterField(
            model_name='criterio',
            name='programas',
            field=models.JSONField(
                default=list,
                help_text='Nombre de los programas entrecomillados, separados por comas, y todos ellos entre corchetes.<br>Ejemplo: <span style="font-family: monospace;">["PIIDUZ", "PIET"]</span>',
                verbose_name='programas en los que aplicar este criterio',
            ),
        ),
    ]
