# Generated by Django 3.2 on 2021-04-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0017_auto_20210211_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(
                choices=[
                    ('ANULADO', 'Solicitud anulada'),
                    ('BORRADOR', 'Solicitud en preparación'),
                    ('SOLICITADO', 'Solicitud presentada'),
                    ('DENEGADO', 'Denegado por la comisión evaluadora'),
                    ('APROBADO', 'Aprobado por la comisión evaluadora'),
                    ('RECHAZADO', 'Rechazado por el coordinador'),
                    ('ACEPTADO', 'Aceptado por el coordinador'),
                    ('MEM_PRESENTADA', 'Memoria presentada'),
                    ('MEM_NO_ADMITIDA', 'Memoria no admitida por el corrector'),
                    ('MEM_ADMITIDA', 'Memoria admitida por el corrector'),
                ],
                default='BORRADOR',
                max_length=63,
            ),
        ),
    ]
