# Generated by Django 4.0.3 on 2022-03-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0018_remove_proyecto_evaluador_alter_criterio_programas'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='descripcion_txt',
            field=models.TextField(
                max_length=4095, null=True, verbose_name='Descripción en texto plano'
            ),
        ),
        migrations.AlterField(
            model_name='criterio',
            name='programas',
            field=models.JSONField(
                default=list,
                help_text='Nombre de los programas entrecomillados, separados por comas,\n            y todos ellos entre corchetes.<br>\n            Ejemplo: <span style="font-family: monospace;">["PIIDUZ", "PIET"]</span>',
                verbose_name='programas en los que aplicar este criterio',
            ),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(
                choices=[
                    ('ANULADO', 'Solicitud anulada'),
                    ('BORRADOR', 'Solicitud en preparación'),
                    ('SOLICITADO', 'Solicitud presentada'),
                    ('DENEGADO', 'Denegado por la comisión evaluadora'),
                    ('APROBADO', 'Aprobado por la comisión evaluadora'),
                    ('RECHAZADO', 'Rechazado por el coordinador'),
                    ('ACEPTADO', 'Aceptado por el coordinador'),
                    ('MEM_PRESENTADA', 'Memoria presentada'),
                    ('MEM_NO_ADMITIDA', 'Memoria no admitida por el corrector'),
                    ('MEM_ADMITIDA', 'Memoria admitida por el corrector'),
                    ('FINALIZADO_SIN_MEMORIA', 'Finalizado sin memoria'),
                ],
                default='BORRADOR',
                max_length=63,
            ),
        ),
    ]
