# Generated by Django 4.0 on 2022-03-04 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0017_criterio_programas'),
        ('indo', '0018_remove_proyecto_area'),
    ]

    operations = [
    ]
