# Generated by Django 3.2 on 2021-04-16 11:38

from django.apps import apps as django_apps
from django.db import migrations, models


def create_group(apps, schema_editor):
    group = apps.get_model('auth', 'Group')
    group, created = group.objects.get_or_create(name='Correctores')


def geo_post_migrate_signal(apps, schema_editor):
    """Emit the post-migrate signal during the migration.

    Permissions are not actually created during or after an individual migration,
    but are triggered by a post-migrate signal which is sent after the
    `python manage.py migrate` command completes successfully.

    This is necessary because this permission is used later in this migration.
    """
    indo_config = django_apps.get_app_config('indo')
    models.signals.post_migrate.send(
        sender=indo_config,
        app_config=indo_config,
        verbosity=2,
        interactive=False,
        using=schema_editor.connection.alias,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0018_alter_proyecto_estado'),
    ]

    operations = [
        migrations.RunPython(create_group),
        migrations.RunPython(geo_post_migrate_signal),
    ]
