# Generated by Django 4.0 on 2022-03-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0019_merge_20220304_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterio',
            name='programas',
            field=models.JSONField(default=list, help_text='Nombre de los programas entrecomillados, separados por comas, y todos ellos entre corchetes.<br>Ejemplo: <span style="font-family: monospace;">["PIIDUZ", "PIET"]</span>', verbose_name='programas en los que aplicar este criterio'),
        ),
    ]
