# Generated by Django 3.2 on 2021-04-22 11:32

from django.apps import apps as django_apps
from django.contrib.auth.management import create_permissions
from django.db import migrations, models


def migrate_permissions(apps, schema_editor):
    """Create the pending permissions.

    Permissions are not actually created during or after an individual migration,
    but are triggered by a post-migrate signal which is sent after the
    `python manage.py migrate` command completes successfully.

    This is necessary so that we can add the permission to a group in this migration.
    """
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=2)
        app_config.models_module = None


def add_permission_to_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    gestores = Group.objects.get(name='Gestores')

    gestionar_correctores = Permission.objects.get(codename='gestionar_correctores')
    gestores.permissions.add(gestionar_correctores)
    asignar_correctores = Permission.objects.get(codename='asignar_correctores')
    gestores.permissions.add(asignar_correctores)


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0019_auto_20210416_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='RightsSupport',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
            ],
            options={
                'permissions': (
                    ('gestionar_correctores', 'Puede añadir/quitar usuarios al grupo Correctores'),
                    ('asignar_correctores', 'Puede asignar un corrector de memoria a un proyecto'),
                ),
                'managed': False,
            },
        ),
        migrations.RunPython(migrate_permissions),
        migrations.RunPython(add_permission_to_group),
    ]
