# Generated by Django 3.2 on 2021-04-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0020_rightssupport'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='es_publicable',
            field=models.BooleanField(null=True, verbose_name='¿Publicar la memoria?'),
        ),
    ]
