# Generated by Django 4.0 on 2022-03-14 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0018_remove_proyecto_evaluador_alter_criterio_programas'),
        ('indo', '0020_alter_criterio_programas'),
    ]

    operations = [
    ]
