# Generated by Django 4.0.4 on 2022-05-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0020_proyecto_financiacion_txt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linea',
            name='nombre',
            field=models.CharField(max_length=191),
        ),
    ]
