# Generated by Django 4.0 on 2022-03-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0021_merge_20220314_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterio',
            name='programas',
            field=models.JSONField(default=list, help_text='Nombre de los programas entrecomillados, separados por comas,\n            y todos ellos entre corchetes.<br>\n            Ejemplo: <span style="font-family: monospace;">["PIIDUZ", "PIET"]</span>', verbose_name='programas en los que aplicar este criterio'),
        ),
    ]
