# Generated by Django 4.0.4 on 2022-05-27 08:24

from django.contrib.auth.management import create_permissions
from django.db import migrations


def add_permissions_to_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    gestores = Group.objects.get(name='Gestores')
    zaguan = Permission.objects.get(codename='zaguan')
    gestores.permissions.add(zaguan)


def migrate_permissions(apps, schema_editor):
    """Create the pending permissions.

    Permissions are not actually created during or after an individual migration,
    but are triggered by a post-migrate signal which is sent after the
    `python manage.py migrate` command completes successfully.

    This is necessary so that we can add the permission to a group in this migration.
    """
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=2)
        app_config.models_module = None


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0021_alter_linea_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={
                'permissions': [
                    ('listar_proyectos', 'Puede ver el listado de todos los proyectos.'),
                    ('ver_proyecto', 'Puede ver cualquier proyecto.'),
                    ('editar_proyecto', 'Puede editar cualquier proyecto en cualquier momento.'),
                    (
                        'listar_evaluaciones',
                        'Puede ver el listado de evaluaciones de los proyectos.',
                    ),
                    ('listar_evaluadores', 'Puede ver el listado de evaluadores.'),
                    ('editar_evaluadores', 'Puede editar los evaluadores de un proyecto.'),
                    (
                        'editar_resolucion',
                        'Puede modificar la resolución de la Comisión Evaluadora.',
                    ),
                    ('listar_correctores', 'Puede ver el listado de correctores.'),
                    ('editar_corrector', 'Puede modificar el corrector de un proyecto.'),
                    ('ver_evaluacion', 'Puede ver la evaluación de cualquier proyecto.'),
                    ('ver_memorias', 'Puede ver el listado y cualquier memoria de proyecto.'),
                    ('ver_up', 'Puede ver el listado de UP y gastos de los proyectos.'),
                    ('ver_economico', 'Puede ver/editar el cierre económico de los proyectos.'),
                    ('zaguan', 'Puede enviar memorias al repositorio institucional.'),
                ]
            },
        ),
        migrations.RunPython(migrate_permissions),
        migrations.RunPython(add_permissions_to_groups),
    ]
