# Generated by Django 4.0.5 on 2022-06-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0022_alter_proyecto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='puntuacion',
            field=models.DecimalField(
                decimal_places=1, max_digits=3, null=True, verbose_name='Puntuación obtenida'
            ),
        ),
    ]
