# Generated by Django 3.2 on 2021-05-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0022_alter_proyecto_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centro',
            name='unidad_gasto',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='unidad_gasto',
        ),
        migrations.AddField(
            model_name='centro',
            name='unidad_planificacion',
            field=models.CharField(
                blank=True, max_length=3, null=True, verbose_name='unidad de planificación'
            ),
        ),
        migrations.AddField(
            model_name='departamento',
            name='unidad_planificacion',
            field=models.CharField(
                blank=True, max_length=3, null=True, verbose_name='unidad de planificación'
            ),
        ),
    ]
