# Generated by Django 4.0 on 2022-03-21 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0020_proyecto_financiacion_txt'),
        ('indo', '0022_alter_criterio_programas'),
    ]

    operations = [
    ]
