# Generated by Django 4.0.4 on 2022-05-11 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0021_alter_linea_nombre'),
        ('indo', '0023_merge_20220321_1302'),
    ]

    operations = [
    ]
