# Generated by Django 4.0.4 on 2022-06-02 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0022_alter_proyecto_options'),
        ('indo', '0024_merge_20220511_1035'),
    ]

    operations = [
    ]
