# Generated by Django 4.0.4 on 2022-06-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0025_merge_20220602_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='puntuacion',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Puntuación obtenida'),
        ),
    ]
