# Generated by Django 4.1.5 on 2023-01-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0025_auto_20220627_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='tiene_infografia',
            field=models.BooleanField(default=False, verbose_name='¿Tiene infografía?'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='campos',
            field=models.TextField(
                help_text='Nombres de los campos que tendrá una solicitud de proyecto del programa (JSON). Ej: ["contexto", "objetivos", "metodos_estudio", "mejoras", "continuidad"]',
                null=True,
            ),
        ),
    ]
