# Generated by Django 4.1.5 on 2023-02-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0026_proyecto_tiene_infografia_alter_programa_campos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centro',
            name='tratamiento_decano',
            field=models.CharField(
                blank=True,
                help_text='Decano/a ó director(a).',
                max_length=254,
                null=True,
                verbose_name='cargo',
            ),
        ),
    ]
