# Generated by Django 4.0.4 on 2022-06-14 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0023_alter_proyecto_puntuacion'),
        ('indo', '0026_alter_proyecto_puntuacion'),
    ]

    operations = [
    ]
