# Generated by Django 4.1.7 on 2023-03-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indo", "0027_alter_centro_tratamiento_decano"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proyecto",
            name="ayuda",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Las normas de la convocatoria establecen el importe máximo que se puede solicitar según el programa.",
                verbose_name="Ayuda económica solicitada",
            ),
        ),
    ]
