# Generated by Django 4.0.4 on 2022-06-27 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0025_auto_20220627_1059'),
        ('indo', '0027_merge_20220614_1334'),
    ]

    operations = [
    ]
