# Generated by Django 4.1.5 on 2023-01-19 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0026_proyecto_tiene_infografia_alter_programa_campos'),
        ('indo', '0028_merge_20220627_1335'),
    ]

    operations = []
