# Generated by Django 4.1.7 on 2023-04-14 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0028_alter_proyecto_ayuda'),
        ('indo', '0029_merge_20230119_1302'),
    ]

    operations = []
