# Generated by Django 5.2.11 on 2026-02-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0030_merge_20230414_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='num_max_participantes',
            field=models.PositiveSmallIntegerField(
                null=True, verbose_name='Número máximo de participantes por proyecto'
            ),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='observaciones',
            field=models.TextField(
                help_text='Sólo visibles para los gestores de esta aplicación, no por los coordinadores.',
                null=True,
                verbose_name='Observaciones internas',
            ),
        ),
    ]
