# Generated by Django 5.2.11 on 2026-02-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0031_programa_num_max_participantes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='num_max_participantes',
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='num_max_participantes',
            field=models.PositiveSmallIntegerField(
                null=True, verbose_name='Número máximo de participantes por proyecto'
            ),
        ),
    ]
