# Generated by Django 5.2.11 on 2026-02-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0032_remove_programa_num_max_participantes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='num_max_coordinaciones',
            field=models.PositiveSmallIntegerField(
                default=2,
                verbose_name='número máximo de proyectos que puede coordinar una persona',
            ),
        ),
    ]
