# Generated by Django 5.2.11 on 2026-02-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0033_convocatoria_num_max_coordinaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='num_max_coordinaciones',
            field=models.PositiveSmallIntegerField(
                null=True,
                verbose_name='número máximo de proyectos que puede coordinar una persona',
            ),
        ),
    ]
