# Generated by Django 5.2.11 on 2026-02-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0034_alter_convocatoria_num_max_coordinaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='miembro_cifice',
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name='Ser miembro de un grupo de innovación reconocido por CIFICE',
            ),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='participantes_iberus',
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name='Incluye participantes de otras universidades del Campus Iberus',
            ),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='participantes_unita',
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name='Incluye participantes de otras universidades de la Alianza Unita Montium no incluidas en el campus Iberus',
            ),
        ),
    ]
