# Generated by Django 5.2.11 on 2026-02-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0035_proyecto_miembro_cifice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='observaciones_financiacion',
            field=models.TextField(
                blank=True, null=True, verbose_name='Observaciones financiación'
            ),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='miembro_cifice',
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name='Es miembro de un grupo de innovación reconocido por CIFICE',
            ),
        ),
    ]
