# Generated by Django 5.2.11 on 2026-02-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0036_proyecto_observaciones_financiacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='observaciones_financiacion',
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name='Relación detallada, si procede, de todos los gastos justificables para la realización del proyecto',
            ),
        ),
    ]
