# Generated by Django 5.2.11 on 2026-05-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indo', '0038_alter_proyecto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='puntuacion',
            field=models.DecimalField(
                decimal_places=2, max_digits=4, null=True, verbose_name='Puntuación obtenida'
            ),
        ),
    ]
