# Generated by Django 2.2.1 on 2019-05-31 12:56

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('accounts', '0002_auto_20190314_0819')]

    operations = [
        migrations.AlterModelManagers(name='customuser', managers=[('objects', accounts.models.CustomUserManager())])
    ]
