# Generated by Django 3.2 on 2021-04-29 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190531_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('last_name', 'last_name_2', 'first_name')},
        ),
    ]
