# Generated by Django 4.0.3 on 2022-03-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_orcid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cuerpo_pod',
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name='Cuerpo POD'
            ),
        ),
    ]
